### PR TITLE
fixtures: move module dependent imports inside

### PR DESCRIPTION
**Pull request by egabancho**
* Moves module dependent imports inside the fixture functions in order
  to decouple dependencies for Invenio apps or modules that might not be
  using them.

### CODE REVIEW

**Comment by egabancho** [comment]
Yeap, you are right, I should have written a better description on the commit message.

**Comment by lnielsen** [comment]
You'll have to start adding copyright statements now :-) On each file you fix :-)

"Copyright (C) 2018 Esteban Garbancho."

**Comment by egabancho** [comment]
Should I update also the AUTHORS file or will get update with the release? 
(probably I should make a release commit)

**Comment by lnielsen** [comment]
AUTHORS we can update when we release - needs an automated tool probably.

**Pull request merged**
